service: react-node-app
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2
functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: GET
          cors: true
